# FROM ghcr.io/slint-ui/slint/armv7-unknown-linux-gnueabihf
FROM ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:0.2.5
# RUN apt-get update && apt-get upgrade -y
# RUN apt-get install libasound-dev libasound-dev:armhf -y
RUN apt-get install -y g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 

