[package]
name = "rust_from_cpp"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_from_cpp"
crate-type = ["staticlib","rlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

